version: "3.9"  # nên dùng >= 3.5 để hỗ trợ ipam
services:
  master:
    build: .
    command: ./app master 12345
    deploy:
      resources:
        limits:
          cpus: "2.0"      # Docker Compose v3 yêu cầu phần này khi dùng với swarm mode
    cpuset: "0-1"          # Chỉ cho phép container dùng CPU core 0 và 1
    networks:
      train_net:
        ipv4_address: 172.31.0.2

  slaver:
    build: .
    command: ./app slaver 12345 172.31.0.2
    deploy:
      resources:
        limits:
          cpus: "2.0"      # Docker Compose v3 yêu cầu phần này khi dùng với swarm mode
    cpuset: "2-3"          # Chỉ cho phép container dùng CPU core 2 và 3
    depends_on:
      - master
    networks:
      train_net:
        ipv4_address: 172.31.0.3
    restart: on-failure

networks:
  train_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16