FROM gcc:9

RUN apt-get update && apt-get install -y \
    make \
    gdb \
    valgrind \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy source code
COPY data/ ./data/
COPY matrix/ ./matrix/
COPY neural/ ./neural/
COPY socket/ ./socket/
COPY util/ ./util/
COPY apps/ ./apps/
COPY Makefile .
COPY Makefile.con .
COPY Makefile.async .
COPY config/ ./config/

# Build parameter server
RUN make -f Makefile.async parameter_server

EXPOSE 12345

ENTRYPOINT ["./parameter_server"]